### ISSUE TITLE
Dead link of the paper that was under review in ICLR2019

### ISSUE THREAD

**Issue by dosssman** [YuhangSong/DEHRL#23]
Greetings.

Thank you for open sourcing the code of your work on DEHRL.

In the [Montezuma related section](https://github.com/YuhangSong/DEHRL#game-montezumarevengenoframeskip-v4), you referenced a paper that was under review for 2019 at that time, but the provided dropbox link does not seem to be available anymore.

Quite some time have passed now so could you please add the reference of the paper itself ?

Thank you for your time.

**Comment by IceClear** [comment]
I think you are finding this one: https://github.com/vik-goel/MOREL. I realized the segmentation part of this work in pytorch and I think it is an interesting work.

**Comment by dosssman** [comment]
Thanks. Appreciate it.
